import { CatalogItemDocument } from "../../src/types/catalog";
import { Fuel } from "../../src/types/vehicle";

export type CatalogItemSeed = Omit<
  CatalogItemDocument,
  "_id" | "createdAt" | "updatedAt"
>;

const COMBUSTION: Fuel[] = [
  "flex",
  "gasoline",
  "ethanol",
  "diesel",
  "cng",
  "hybrid",
];

const ELECTRIFIED: Fuel[] = ["electric", "hybrid"];

export const catalogItemsSeed: CatalogItemSeed[] = [
  {
    code: "ENGINE_OIL",
    name: "Óleo do motor + filtro",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 10000,
    defaultIntervalMonths: 12,
    criticality: "critical",
    whatItIs: "Óleo lubrificante do motor e o filtro que retém as impurezas em suspensão.",
    whyItMatters: "Óleo velho perde a película de proteção e o motor começa a se desgastar por dentro.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["ENGINE_AIR_FILTER"],
    active: true,
  },
  {
    code: "ENGINE_AIR_FILTER",
    name: "Filtro de ar do motor",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 15000,
    defaultIntervalMonths: 12,
    criticality: "medium",
    whatItIs: "Filtro que limpa o ar antes de ele entrar na câmara de combustão.",
    whyItMatters: "Entupido, sufoca o motor: sobe o consumo e cai o desempenho.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["ENGINE_OIL"],
    active: true,
  },
  {
    code: "FUEL_FILTER",
    name: "Filtro de combustível",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 30000,
    defaultIntervalMonths: 24,
    criticality: "high",
    whatItIs: "Filtro que retém sujeira e água do combustível antes da bomba e dos bicos.",
    whyItMatters: "Saturado, faz o carro falhar em aceleração e pode danificar a bomba de combustível.",
    appliesTo: { fuel: ["flex", "gasoline", "ethanol", "diesel", "cng"] },
    active: true,
  },
  {
    code: "SPARK_PLUGS",
    name: "Velas de ignição",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: 36,
    criticality: "high",
    whatItIs: "Peças que geram a faísca que inicia a queima da mistura ar-combustível.",
    whyItMatters: "Gastas, provocam falha de ignição, marcha lenta irregular e consumo alto.",
    appliesTo: { fuel: ["flex", "gasoline", "ethanol", "cng", "hybrid"], note: "Motor diesel não usa vela de ignição." },
    bundledWith: ["IGNITION_CABLES"],
    active: true,
  },
  {
    code: "IGNITION_CABLES",
    name: "Cabos de vela",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    criticality: "medium",
    whatItIs: "Cabos que levam a alta tensão da bobina até cada vela.",
    whyItMatters: "Com isolamento ressecado, a corrente fuga e o motor perde força e falha na chuva.",
    appliesTo: { fuel: ["flex", "gasoline", "ethanol", "cng"], note: "Não se aplica a motor com bobina individual por cilindro." },
    bundledWith: ["SPARK_PLUGS"],
    active: true,
  },
  {
    code: "IGNITION_COIL",
    name: "Bobina de ignição",
    category: "engine",
    dueType: "inspection",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Componente que eleva a tensão da bateria ao nível necessário para a faísca.",
    whyItMatters: "Quando falha, o cilindro para de queimar e acende a luz de injeção.",
    appliesTo: { fuel: ["flex", "gasoline", "ethanol", "cng", "hybrid"] },
    active: true,
  },
  {
    code: "TIMING_BELT_KIT",
    name: "Correia dentada + tensor + rolamento",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    criticality: "critical",
    whatItIs: "Conjunto que sincroniza o giro do virabrequim com o comando de válvulas.",
    whyItMatters: "Se romper, as válvulas batem nos pistões e o prejuízo vira motor novo.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["WATER_PUMP", "ACCESSORY_BELT"],
    active: true,
  },
  {
    code: "TIMING_CHAIN",
    name: "Corrente de comando",
    category: "engine",
    dueType: "inspection",
    defaultIntervalKm: 100000,
    defaultIntervalMonths: null,
    criticality: "high",
    whatItIs: "Alternativa metálica à correia dentada, com vida mais longa.",
    whyItMatters: "Esticada, adianta o ponto, faz barulho no motor frio e pode pular dente.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "ACCESSORY_BELT",
    name: "Correia do alternador (poly-V)",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 50000,
    defaultIntervalMonths: 48,
    criticality: "high",
    whatItIs: "Correia que aciona alternador, direção hidráulica e compressor do ar.",
    whyItMatters: "Se arrebentar, o carro para de carregar a bateria e a direção fica pesada.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["TIMING_BELT_KIT"],
    active: true,
  },
  {
    code: "WATER_PUMP",
    name: "Bomba d'água",
    category: "engine",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    criticality: "critical",
    whatItIs: "Bomba que circula o líquido de arrefecimento pelo motor e pelo radiador.",
    whyItMatters: "Travada ou vazando, o motor superaquece e empena o cabeçote.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["TIMING_BELT_KIT", "COOLANT"],
    active: true,
  },
  {
    code: "INJECTOR_CLEANING",
    name: "Limpeza de bicos injetores",
    category: "engine",
    dueType: "km",
    defaultIntervalKm: 30000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Limpeza do spray dos bicos que pulverizam o combustível.",
    whyItMatters: "Bico sujo espirra em vez de pulverizar: consumo sobe e a marcha lenta oscila.",
    appliesTo: { fuel: ["flex", "gasoline", "ethanol", "diesel"] },
    active: true,
  },
  {
    code: "THROTTLE_BODY_CLEANING",
    name: "Limpeza do corpo de borboleta",
    category: "engine",
    dueType: "km",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: null,
    criticality: "low",
    whatItIs: "Limpeza da peça que dosa a entrada de ar no motor.",
    whyItMatters: "Com borra acumulada, a marcha lenta cai e o carro morre em semáforo.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "PCV_VALVE",
    name: "Válvula PCV / respiro do motor",
    category: "engine",
    dueType: "km",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: null,
    criticality: "low",
    whatItIs: "Válvula que devolve os gases do cárter para a admissão.",
    whyItMatters: "Entupida, pressuriza o motor e força vazamento pelos retentores.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "OXYGEN_SENSOR",
    name: "Sonda lambda",
    category: "engine",
    dueType: "km",
    defaultIntervalKm: 80000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Sensor que mede o oxigênio no escapamento e corrige a mistura.",
    whyItMatters: "Preguiçosa, engorda a mistura, aumenta o consumo e mata o catalisador.",
    appliesTo: { fuel: ["flex", "gasoline", "ethanol", "cng", "hybrid"] },
    active: true,
  },
  {
    code: "ENGINE_MOUNTS",
    name: "Coxins do motor",
    category: "engine",
    dueType: "inspection",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Suportes de borracha que prendem o motor e absorvem a vibração.",
    whyItMatters: "Ressecados, transmitem trepidação para o volante e batem ao engatar marcha.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "COOLANT",
    name: "Fluido de arrefecimento",
    category: "cooling",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 36,
    criticality: "critical",
    whatItIs: "Líquido que troca calor com o motor e protege contra corrosão.",
    whyItMatters: "Velho, perde o aditivo, corrói por dentro e deixa o motor ferver.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["WATER_PUMP", "RADIATOR_HOSES"],
    active: true,
  },
  {
    code: "RADIATOR_HOSES",
    name: "Mangueiras do radiador",
    category: "cooling",
    dueType: "inspection",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Mangueiras que levam o líquido entre motor e radiador.",
    whyItMatters: "Ressecadas, estouram sem aviso e o motor superaquece em minutos.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["COOLANT"],
    active: true,
  },
  {
    code: "THERMOSTAT",
    name: "Válvula termostática",
    category: "cooling",
    dueType: "km",
    defaultIntervalKm: 80000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Válvula que segura o líquido até o motor atingir a temperatura de trabalho.",
    whyItMatters: "Travada fechada, ferve o motor; travada aberta, ele nunca aquece e gasta mais.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "RADIATOR_CAP",
    name: "Tampa do radiador",
    category: "cooling",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 48,
    criticality: "low",
    whatItIs: "Tampa que mantém o sistema pressurizado na medida certa.",
    whyItMatters: "Com a mola fraca, o sistema perde pressão e o líquido evapora antes da hora.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "BRAKE_FLUID",
    name: "Fluido de freio",
    category: "brakes",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    criticality: "critical",
    whatItIs: "Fluido que transmite a força do pedal até as rodas.",
    whyItMatters: "Absorve água com o tempo: em frenagem forte ferve e o pedal vai ao fundo.",
    active: true,
  },
  {
    code: "BRAKE_PADS_FRONT",
    name: "Pastilhas dianteiras",
    category: "brakes",
    dueType: "inspection",
    defaultIntervalKm: 10000,
    defaultIntervalMonths: null,
    criticality: "critical",
    whatItIs: "Material de atrito que aperta o disco dianteiro para frear.",
    whyItMatters: "No fim do curso, o metal raspa o disco e a distância de frenagem dispara.",
    bundledWith: ["BRAKE_DISCS"],
    active: true,
  },
  {
    code: "BRAKE_PADS_REAR",
    name: "Pastilhas traseiras",
    category: "brakes",
    dueType: "inspection",
    defaultIntervalKm: 20000,
    defaultIntervalMonths: null,
    criticality: "high",
    whatItIs: "Material de atrito do freio traseiro a disco.",
    whyItMatters: "Gastas, desequilibram a frenagem e comprometem a estabilidade.",
    active: true,
  },
  {
    code: "BRAKE_DISCS",
    name: "Discos de freio",
    category: "brakes",
    dueType: "inspection",
    defaultIntervalKm: 20000,
    defaultIntervalMonths: null,
    criticality: "high",
    whatItIs: "Discos metálicos que as pastilhas apertam para parar a roda.",
    whyItMatters: "Abaixo da espessura mínima, empenam, trepidam no pedal e perdem eficiência.",
    bundledWith: ["BRAKE_PADS_FRONT"],
    active: true,
  },
  {
    code: "BRAKE_DRUMS_SHOES",
    name: "Tambores e lonas",
    category: "brakes",
    dueType: "inspection",
    defaultIntervalKm: 30000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Conjunto de freio traseiro a tambor, comum em carros de entrada.",
    whyItMatters: "Lona gasta reduz o freio traseiro e desregula o freio de mão.",
    bundledWith: ["PARKING_BRAKE"],
    active: true,
  },
  {
    code: "PARKING_BRAKE",
    name: "Freio de estacionamento (regulagem)",
    category: "brakes",
    dueType: "inspection",
    defaultIntervalKm: 20000,
    defaultIntervalMonths: null,
    criticality: "low",
    whatItIs: "Ajuste do curso do cabo do freio de mão.",
    whyItMatters: "Frouxo, deixa o carro descer sozinho na ladeira.",
    active: true,
  },
  {
    code: "MANUAL_GEARBOX_OIL",
    name: "Óleo do câmbio manual",
    category: "transmission",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    criticality: "high",
    whatItIs: "Lubrificante das engrenagens e sincronizadores do câmbio manual.",
    whyItMatters: "Degradado, endurece a troca de marchas e desgasta os sincronizadores.",
    appliesTo: { fuel: COMBUSTION, transmission: ["manual"] },
    active: true,
  },
  {
    code: "AUTO_GEARBOX_OIL",
    name: "Óleo do câmbio automático",
    category: "transmission",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    criticality: "high",
    whatItIs: "Fluido que lubrifica e aciona os comandos hidráulicos do câmbio automático.",
    whyItMatters: "Queimado, provoca trancos, patinação e a troca do câmbio custa mais que o carro vale.",
    appliesTo: { fuel: COMBUSTION, transmission: ["automatic", "automated"] },
    active: true,
  },
  {
    code: "CVT_FLUID",
    name: "Fluido do câmbio CVT",
    category: "transmission",
    dueType: "both",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: 48,
    criticality: "high",
    whatItIs: "Fluido específico da transmissão continuamente variável.",
    whyItMatters: "É o item que mais mata CVT: fora do prazo, a correia patina e o câmbio se perde.",
    appliesTo: { fuel: COMBUSTION, transmission: ["cvt"] },
    active: true,
  },
  {
    code: "CLUTCH_KIT",
    name: "Kit de embreagem",
    category: "transmission",
    dueType: "inspection",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: null,
    criticality: "high",
    whatItIs: "Disco, platô e rolamento que ligam o motor ao câmbio.",
    whyItMatters: "Gasta, patina em subida e pode deixar o carro sem tração no meio do caminho.",
    appliesTo: { fuel: COMBUSTION, transmission: ["manual", "automated"] },
    active: true,
  },
  {
    code: "DIFFERENTIAL_OIL",
    name: "Óleo do diferencial",
    category: "transmission",
    dueType: "km",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Lubrificante das engrenagens que distribuem tração entre as rodas.",
    whyItMatters: "Sem lubrificação boa, o conjunto rosna e some com o dente da coroa.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "POWER_STEERING_FLUID",
    name: "Fluido da direção hidráulica",
    category: "steering_suspension",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 36,
    criticality: "medium",
    whatItIs: "Fluido que dá assistência hidráulica ao volante.",
    whyItMatters: "Velho ou no nível baixo, faz a direção pesar e a bomba roncar.",
    appliesTo: {
      fuel: COMBUSTION,
      note: "Não se aplica a direção elétrica (EPS).",
    },
    active: true,
  },
  {
    code: "SHOCK_ABSORBERS",
    name: "Amortecedores",
    category: "steering_suspension",
    dueType: "inspection",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: null,
    criticality: "high",
    whatItIs: "Componentes que controlam o movimento da suspensão.",
    whyItMatters: "Cansados, o carro flutua, aumenta a distância de frenagem e come pneu.",
    bundledWith: ["SUSPENSION_BUSHINGS", "WHEEL_ALIGNMENT"],
    active: true,
  },
  {
    code: "SUSPENSION_BUSHINGS",
    name: "Buchas e batentes",
    category: "steering_suspension",
    dueType: "inspection",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Peças de borracha que amortecem e alinham os braços da suspensão.",
    whyItMatters: "Gastas, geram barulho em lombada e desregulam o alinhamento.",
    bundledWith: ["SHOCK_ABSORBERS"],
    active: true,
  },
  {
    code: "STEERING_TIE_RODS",
    name: "Terminais e pivôs de direção",
    category: "steering_suspension",
    dueType: "inspection",
    defaultIntervalKm: 40000,
    defaultIntervalMonths: null,
    criticality: "high",
    whatItIs: "Articulações que ligam a direção às rodas.",
    whyItMatters: "Com folga, o volante fica vago e, no limite, a roda perde o comando.",
    bundledWith: ["WHEEL_ALIGNMENT"],
    active: true,
  },
  {
    code: "WHEEL_BEARINGS",
    name: "Rolamentos de roda",
    category: "steering_suspension",
    dueType: "inspection",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Rolamentos que permitem a roda girar com folga mínima.",
    whyItMatters: "Ao ronronar em velocidade, já estão perto de travar a roda.",
    active: true,
  },
  {
    code: "TIRE_ROTATION",
    name: "Rodízio de pneus",
    category: "tires",
    dueType: "km",
    defaultIntervalKm: 10000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Troca de posição dos pneus entre os eixos.",
    whyItMatters: "Sem rodízio, o eixo dianteiro gasta bem antes e você troca dois pneus a mais.",
    bundledWith: ["WHEEL_ALIGNMENT"],
    active: true,
  },
  {
    code: "WHEEL_ALIGNMENT",
    name: "Alinhamento e balanceamento",
    category: "tires",
    dueType: "km",
    defaultIntervalKm: 10000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Ajuste dos ângulos de direção e do equilíbrio das rodas.",
    whyItMatters: "Fora do ajuste, o carro puxa para o lado, vibra e desgasta o pneu na borda.",
    bundledWith: ["TIRE_ROTATION"],
    active: true,
  },
  {
    code: "TIRES",
    name: "Troca dos pneus",
    category: "tires",
    dueType: "both",
    defaultIntervalKm: 50000,
    defaultIntervalMonths: 60,
    criticality: "critical",
    whatItIs: "O único contato do carro com o chão.",
    whyItMatters: "Careca ou ressecado, perde aderência na chuva — é o item que mais causa acidente.",
    bundledWith: ["WHEEL_ALIGNMENT"],
    active: true,
  },
  {
    code: "BATTERY",
    name: "Bateria",
    category: "electrical",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 36,
    criticality: "high",
    whatItIs: "Fonte de energia para dar a partida e alimentar a eletrônica parada.",
    whyItMatters: "Perde carga com a idade e deixa o carro na mão sem dar sinal antes.",
    active: true,
  },
  {
    code: "ALTERNATOR",
    name: "Alternador",
    category: "electrical",
    dueType: "inspection",
    defaultIntervalKm: 80000,
    defaultIntervalMonths: null,
    criticality: "medium",
    whatItIs: "Gerador que recarrega a bateria com o motor em funcionamento.",
    whyItMatters: "Fraco, a bateria descarrega andando e o carro apaga no trânsito.",
    appliesTo: { fuel: COMBUSTION },
    bundledWith: ["ACCESSORY_BELT"],
    active: true,
  },
  {
    code: "STARTER_MOTOR",
    name: "Motor de partida",
    category: "electrical",
    dueType: "inspection",
    defaultIntervalKm: 100000,
    defaultIntervalMonths: null,
    criticality: "low",
    whatItIs: "Motor elétrico que gira o virabrequim na partida.",
    whyItMatters: "Com escovas gastas, a partida falha justo quando você tem pressa.",
    appliesTo: { fuel: COMBUSTION },
    active: true,
  },
  {
    code: "HEADLIGHT_BULBS",
    name: "Lâmpadas do farol",
    category: "electrical",
    dueType: "inspection",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    criticality: "low",
    whatItIs: "Lâmpadas de iluminação dianteira.",
    whyItMatters: "Perdem luminosidade antes de queimar e reduzem o alcance à noite.",
    active: true,
  },
  {
    code: "CABIN_FILTER",
    name: "Filtro do ar-condicionado (cabine)",
    category: "hvac",
    dueType: "both",
    defaultIntervalKm: 15000,
    defaultIntervalMonths: 12,
    criticality: "medium",
    whatItIs: "Filtro que limpa o ar que entra na cabine.",
    whyItMatters: "Sujo, cheira mal, reduz a ventilação e piora a alergia de quem anda no carro.",
    bundledWith: ["AC_SANITIZING"],
    active: true,
  },
  {
    code: "AC_REFRIGERANT",
    name: "Carga de gás do ar-condicionado",
    category: "hvac",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    criticality: "medium",
    whatItIs: "Fluido refrigerante do sistema de ar-condicionado.",
    whyItMatters: "Com carga baixa, o compressor trabalha mal lubrificado e queima.",
    bundledWith: ["AC_COMPRESSOR_OIL"],
    active: true,
  },
  {
    code: "AC_COMPRESSOR_OIL",
    name: "Óleo do compressor do ar-condicionado",
    category: "hvac",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    criticality: "medium",
    whatItIs: "Lubrificante que circula junto com o gás refrigerante.",
    whyItMatters: "Sem ele na medida, o compressor trava e leva junto o condensador.",
    bundledWith: ["AC_REFRIGERANT"],
    active: true,
  },
  {
    code: "AC_SANITIZING",
    name: "Higienização do ar-condicionado",
    category: "hvac",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 12,
    criticality: "low",
    whatItIs: "Limpeza do evaporador e dos dutos de ventilação.",
    whyItMatters: "Sem limpeza, fungo se acumula no evaporador e o ar sai com cheiro.",
    bundledWith: ["CABIN_FILTER"],
    active: true,
  },
  {
    code: "WIPER_BLADES",
    name: "Palhetas do limpador",
    category: "body",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 12,
    criticality: "low",
    whatItIs: "Borrachas que limpam o para-brisa.",
    whyItMatters: "Ressecadas, borram o vidro na chuva e riscam o para-brisa.",
    active: true,
  },
  {
    code: "EV_BATTERY_COOLANT",
    name: "Fluido de arrefecimento da bateria",
    category: "cooling",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 48,
    criticality: "critical",
    whatItIs: "Líquido que controla a temperatura do pacote de baterias de tração e da eletrônica de potência.",
    whyItMatters: "Bateria quente perde autonomia e envelhece rápido; o fluido velho deixa de dar conta da troca de calor.",
    appliesTo: { fuel: ELECTRIFIED },
    active: true,
  },
  {
    code: "EV_TRACTION_BATTERY_CHECK",
    name: "Diagnóstico da bateria de tração",
    category: "electrical",
    dueType: "inspection",
    defaultIntervalKm: null,
    defaultIntervalMonths: 12,
    criticality: "critical",
    whatItIs: "Leitura da saúde da bateria: capacidade restante, equilíbrio entre os módulos e histórico de falhas.",
    whyItMatters: "É a peça mais cara do carro e a que define a autonomia; degradação fora do normal precisa aparecer enquanto a garantia vale.",
    appliesTo: { fuel: ELECTRIFIED },
    active: true,
  },
  {
    code: "EV_HV_CABLES",
    name: "Cabos e conectores de alta tensão",
    category: "electrical",
    dueType: "inspection",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    criticality: "critical",
    whatItIs: "Inspeção dos cabos laranja de alta tensão, conexões e isolamento entre bateria, inversor e motor.",
    whyItMatters: "Isolamento comprometido é risco elétrico sério e costuma dar sintoma antes de virar pane.",
    appliesTo: { fuel: ELECTRIFIED },
    active: true,
  },
  {
    code: "EV_CHARGING_CABLE",
    name: "Cabo e tomada de recarga",
    category: "electrical",
    dueType: "inspection",
    defaultIntervalKm: null,
    defaultIntervalMonths: 12,
    criticality: "medium",
    whatItIs: "Verificação do cabo de recarga, dos pinos do conector e da trava da tomada do carro.",
    whyItMatters: "Pino sujo ou oxidado esquenta, reduz a corrente aceita e pode danificar a porta de recarga.",
    appliesTo: { fuel: ELECTRIFIED },
    active: true,
  },
  {
    code: "EV_REDUCTION_GEARBOX_OIL",
    name: "Óleo da caixa de redução",
    category: "transmission",
    dueType: "both",
    defaultIntervalKm: 60000,
    defaultIntervalMonths: 60,
    criticality: "high",
    whatItIs: "Óleo da caixa de redução que liga o motor elétrico às rodas.",
    whyItMatters: "É o único banho de óleo do trem de força elétrico; degradado, castiga engrenagem e rolamento.",
    appliesTo: { fuel: ["electric"] },
    active: true,
  },
  {
    code: "EV_BRAKE_CALIPER_SERVICE",
    name: "Limpeza e lubrificação das pinças de freio",
    category: "brakes",
    dueType: "time",
    defaultIntervalKm: null,
    defaultIntervalMonths: 24,
    criticality: "high",
    whatItIs: "Desmontagem, limpeza e lubrificação das pinças, com regulagem do curso das pastilhas.",
    whyItMatters: "A frenagem regenerativa faz o freio mecânico trabalhar pouco, e pinça parada agarra, empena disco e come pastilha de um lado só.",
    appliesTo: { fuel: ELECTRIFIED },
    bundledWith: ["BRAKE_PADS_FRONT"],
    active: true,
  },
  {
    code: "HYBRID_BATTERY_FAN_FILTER",
    name: "Filtro do ventilador da bateria híbrida",
    category: "electrical",
    dueType: "both",
    defaultIntervalKm: 20000,
    defaultIntervalMonths: 24,
    criticality: "medium",
    whatItIs: "Filtro do duto de ar que resfria a bateria híbrida, normalmente atrás do banco traseiro.",
    whyItMatters: "Entupido, a bateria trabalha quente, perde rendimento e reduz a vida útil do pacote.",
    appliesTo: { fuel: ["hybrid"] },
    active: true,
  },
];
